# Generated by Django 4.0.2 on 2022-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='regularPost',
            field=models.BooleanField(default=True),
        ),
    ]
