# Generated by Django 4.0.2 on 2022-02-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_options_remove_post_regularpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fbPost',
            field=models.BooleanField(default=False),
        ),
    ]
