# Generated by Django 4.0.2 on 2022-03-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
