# Generated by Django 4.0.2 on 2022-03-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_remove_tag_posts_remove_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
